global using JunoBank.Application.DTOs;
global using JunoBank.Application.Interfaces;
global using JunoBank.Domain.Entities;
global using JunoBank.Domain.Enums;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
